services:
  cache:
    image: memcached:1.6.34
    ports:
      - "11211:11211"
    command:
      - --conn-limit=256
      - --memory-limit=32
      - --threads=2
    networks:
      - mirror_network 

networks:
  mirror_network:
    driver: bridge
